### ISSUE TITLE
无法载入服务器

### ISSUE THREAD

**Issue by yyhhkya** [SlimefunGuguProject/InfinityExpansion#18]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [x] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [x] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/InfinityExpansion/issues)，且没有找到相同的问题

### 问题描述

昨天用的时候还能正常使用的
今天早上起床的时候就发现用不了了
重启服务器后也一样
![T W8JT`RLQN3NM4BA`Q_`H1](https://user-images.githubusercontent.com/87574541/192935191-e4e328e0-3218-46e4-a94b-418c1faf61a4.png)

### 复现步骤

开启服务器无法载入

### 预期行为

正常应该载入成功

### 服务端软件

Paper

### Minecraft 版本

1.16.x

### CS-CoreLib 版本

- [x] 我没有安装CS-CoreLib

### Slimefun版本

2022.07-release

### 插件版本

4

**Comment by yyhhkya** [comment]
这是服务器日志
[latest.log](https://github.com/SlimefunGuguProject/InfinityExpansion/files/9670795/latest.log)

**Comment by ybw0014** [comment]
应该已在最新版本中修复。

该问题是由粘液的存储系统异常导致的。现在应该可以正常开启了。
