### ISSUE TITLE
无尽贪婪的储存可以被粘液原版基础机器分类里的台锯锯成8个木板

### ISSUE THREAD

**Issue by haiman233** [SlimefunGuguProject/InfinityExpansion#19]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/InfinityExpansion/issues)，且没有找到相同的问题

### 问题描述

无尽贪婪的储存可以被粘液原版基础机器分类里的台锯锯成8个木板

### 复现步骤

随便拿一个无尽的储存单元，搭建一个粘液原版的基础机器——台锯，拿着储存单元（里面含物品），右键台锯，会被台锯锯成8个木板，不含物品也是一样

### 预期行为

无尽的储存单元不会被台锯锯掉

### 服务端软件

Paper

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

![QQ图片20230408232600](https://user-images.githubusercontent.com/83174104/230729518-1b34ba3c-6321-48d8-a77b-7829b3bbf9ab.jpg)

### 插件版本

Build 5

**Comment by ybw0014** [comment]
啧，这是本体的问题

**Comment by ybw0014** [comment]
在开发版修了，还没传
