### ISSUE TITLE
无尽报错，无法放置部分无尽物品

### ISSUE THREAD

**Issue by DuoDuoJuZi** [SlimefunGuguProject/InfinityExpansion#22]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/InfinityExpansion/issues)，且没有找到相同的问题

### 问题描述

无尽部分物品在某个区块无法放置，放置后直接消失
报错为提示我去看文件夹
err文件：https://paste.guizhanss.net/9SM4K
服务端核心为定制 融合sp+pa
java为zulu

### 复现步骤

放置奇点构造后直接消失
![6GZB$K~4EK~L5I1H$G5J955](https://github.com/SlimefunGuguProject/InfinityExpansion/assets/105411098/c9cba315-f67f-4a75-8fa2-dbfb67d26bad)

### 预期行为

放置不会消失，而今晚放置后直接消失

### 服务器日志

https://paste.guizhanss.net/9SM4K

### 错误报告

https://paste.guizhanss.net/9SM4K

### 服务端软件

其他 (请在问题描述里写明)

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

v2023.2

### 插件版本

Build 5 zh-CN(SlimefunGuguProject) (git 018bfe1)

**Comment by ybw0014** [comment]
你这日志里无尽是#7，从#6开始粘液本体需要2023.06以上

**Comment by ybw0014** [comment]
你也可以退回#5并关闭自动更新
