### ISSUE TITLE
控制台打印错误 REINFORCED_STORAGE 玩家存储物品丢失

### ISSUE THREAD

**Issue by aesopcmc** [SlimefunGuguProject/InfinityExpansion#24]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/InfinityExpansion/issues)，且没有找到相同的问题

### 问题描述

高级存储物品有时候会变成原木，特别是服务器崩溃重启，存储的物品会丢失

### 复现步骤

非正常崩溃

### 预期行为

高级存储里的物品不丢失，不变为普通原木方块

### 服务器日志

https://paste.guizhanss.net/rV6Ta

### 错误报告

https://paste.guizhanss.net/exFcT

### 服务端软件

Spigot

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

 Slimefun v2023.06-release

### 插件版本

InfinityExpansion vBuild 7 zh-CN(SlimefunGuguProject) (git 00b37e0)

**Comment by ybw0014** [comment]
迁移前存储的数据已经丢失，迁移后就报错了

**Comment by ybw0014** [comment]
Duplicate of #21
