### ISSUE TITLE
无尽存储在使用的时候，会出现无法使用的问题

### ISSUE THREAD

**Issue by Thexiaoyuqaq** [SlimefunGuguProject/InfinityExpansion#29]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/InfinityExpansion/issues)，且没有找到相同的问题

### 问题描述

1.使用 基础储存单元 会变成普通项目
2.打开的时候能显示数量中间的格子不显示所放物品

我尝试在issues寻找解决方法，但并没有任何答案，虽然有个相同的问题，但是似乎不太完整，也比较老旧
![2~`@X0}$YM6ULW38SW3UY%7](https://github.com/SlimefunGuguProject/InfinityExpansion/assets/50231954/7b716176-6350-4e2c-bdac-535043d57447)

### 复现步骤

1. 随机性的出现问题

### 预期行为

可以正常使用并正常打开，并不会出现方块变为橡木

### 服务器日志

https://paste.guizhanss.net/QCju1

### 错误报告

https://paste.guizhanss.net/Yl42d

### 服务端软件

Paper

### Minecraft 版本

1.18.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

v40c4284-Beta

### 插件版本

vBuild 16 zh-CN(ybw0014) (git d51a683)

**Comment by ybw0014** [comment]
你使用的版本过旧
